export const PAYMENT_METHODS = [
  {
    id:           'cod',
    label:        'Cash on Delivery',
    sublabel:     'Pay when order arrives',
    icon:         '💵',
    bgColor:      'rgba(45,106,45,0.2)',
    textColor:    '#5cb85c',
    deliveryFee:  299,
    freeDelivery: false,
    available:    true,
    instructions: 'Our rider will collect PKR 299 delivery + product cost at your door.',
  },
  {
    id:            'jazzcash',
    label:         'JazzCash',
    sublabel:      'FREE Delivery 🎁',
    icon:          '📱',
    bgColor:       'rgba(237,28,36,0.15)',
    textColor:     '#ff6b6b',
    deliveryFee:   0,
    freeDelivery:  true,
    available:     true,
    accountNumber: '0301-1837160',
    accountName:   'Vital Agro',
    instructions:  'Send full order amount to JazzCash 0301-1837160. Screenshot → WhatsApp.',
  },
  {
    id:            'easypaisa',
    label:         'Easypaisa',
    sublabel:      'FREE Delivery 🎁',
    icon:          '💚',
    bgColor:       'rgba(29,185,84,0.15)',
    textColor:     '#1db954',
    deliveryFee:   0,
    freeDelivery:  true,
    available:     true,
    accountNumber: '0301-1837160',
    accountName:   'Vital Agro',
    instructions:  'Send full order amount to Easypaisa 0301-1837160. Screenshot → WhatsApp.',
  },
  {
    id:            'meezan',
    label:         'Bank Transfer',
    sublabel:      'FREE Delivery 🎁',
    icon:          '🏦',
    bgColor:       'rgba(0,102,51,0.2)',
    textColor:     '#4ade80',
    deliveryFee:   0,
    freeDelivery:  true,
    available:     true,
    accountNumber: 'PK00MEZN000000000000',
    accountName:   'Vital Agro Chemical Industries',
    instructions:  'Transfer to Meezan Bank. Send slip on WhatsApp for confirmation.',
  },
];

export const getDeliveryFee = (methodId) =>
  PAYMENT_METHODS.find(m => m.id === methodId)?.deliveryFee ?? 299;
